artifact_uri: file:///home/mle-user/mle_projects/mlflow/mlflow_experiments_store/0/6d1faa8ba1ed4aebb72375341aac9868/artifacts
end_time: 1743144515322
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6d1faa8ba1ed4aebb72375341aac9868
run_name: Default
run_uuid: 6d1faa8ba1ed4aebb72375341aac9868
source_name: ''
source_type: 4
source_version: ''
start_time: 1743144515310
status: 3
tags: []
user_id: mle-user
