artifact_uri: file:///home/mle-user/mlflow/mlflow_experiments_store/0/819f3d537c494701aad226c55bdf4498/artifacts
end_time: 1743107071916
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 819f3d537c494701aad226c55bdf4498
run_name: Default
run_uuid: 819f3d537c494701aad226c55bdf4498
source_name: ''
source_type: 4
source_version: ''
start_time: 1743107071892
status: 3
tags: []
user_id: mle-user
