artifact_uri: file:///home/mle-user/mlflow/mlflow_experiments_store/0/c024a67599aa4407b353a76824cbb3c4/artifacts
end_time: 1743107467330
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c024a67599aa4407b353a76824cbb3c4
run_name: Default
run_uuid: c024a67599aa4407b353a76824cbb3c4
source_name: ''
source_type: 4
source_version: ''
start_time: 1743107467295
status: 3
tags: []
user_id: mle-user
