artifact_uri: file:///home/mle-user/mlflow/mlflow_experiments_store/0/48a42604891e44a1a67aeca7125f3bd3/artifacts
end_time: 1743108161288
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 48a42604891e44a1a67aeca7125f3bd3
run_name: Default
run_uuid: 48a42604891e44a1a67aeca7125f3bd3
source_name: ''
source_type: 4
source_version: ''
start_time: 1743108161269
status: 3
tags: []
user_id: mle-user
